In [222]:
import pandas as pd

lay_acc=pd.read_csv("MyActivityDataset/Laying1_Acc.csv",header=None)
lay_gyro=pd.read_csv("MyActivityDataset/Laying1_Gyro.csv",header=None)

# sit1_acc=pd.read_csv("MyActivityDataset/Sit1_Acc.csv",header=None)
# sit1_gyro=pd.read_csv("MyActivityDataset/Sit1_Gyro.csv",header=None)

sit_acc=pd.read_csv("MyActivityDataset/Sit2_Acc.csv",header=None)
sit_gyro=pd.read_csv("MyActivityDataset/Sit2_Gyro.csv",header=None)

# my_data_train_X = my_data_train_X.drop('Unnamed: 0', 1)
# my_data_test_X = my_data_test_X.drop('Unnamed: 0', 1)

run_acc=pd.read_csv("MyActivityDataset/Run2_Acc.csv",header=None)
run_gyro=pd.read_csv("MyActivityDataset/Run2_Gyro.csv",header=None)

for i in range(3,8):
    run_acc=run_acc.append(pd.read_csv("MyActivityDataset/Run%d_Acc.csv"%i,header=None))
    run_gyro=run_gyro.append(pd.read_csv("MyActivityDataset/Run%d_Gyro.csv"%i,header=None))

walk_acc=pd.read_csv("MyActivityDataset/walk2_Acc.csv",header=None)
walk_gyro=pd.read_csv("MyActivityDataset/walk2_Gyro.csv",header=None)

for i in range(2,11):
    walk_acc=walk_acc.append(pd.read_csv("MyActivityDataset/walk%d_Acc.csv"%i,header=None))
    walk_gyro=walk_gyro.append(pd.read_csv("MyActivityDataset/walk%d_Gyro.csv"%i,header=None))

In [253]:
lables=['Running','Sitting','Walking','Laying']

In [223]:
run_acc.shape

(14043, 3)

In [224]:
walk_acc.shape

(10038, 3)

In [234]:
walk_gyro.shape

(10024, 3)

In [225]:
lay_acc.shape

(15038, 3)

In [226]:
sit_acc.shape

(15038, 3)

In [227]:
pd.DataFrame(sit_acc.iloc[0:50,0]).T

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
0,-0.246004,-0.295085,-0.304662,-0.299275,-0.313042,-0.290895,-0.305261,-0.332794,-0.344166,-0.286706,...,-0.346561,-0.349553,-0.366911,-0.377685,-0.410606,-0.374094,-0.308253,-0.307056,-0.309451,-0.300472

In [241]:
run_acc_extended=pd.DataFrame()
run_gyro_extended=pd.DataFrame()
sit_acc_extended=pd.DataFrame()
sit_gyro_extended=pd.DataFrame()
walk_acc_extended=pd.DataFrame()
walk_gyro_extended=pd.DataFrame()
lay_acc_extended=pd.DataFrame()
lay_gyro_extended=pd.DataFrame()

step=50

for i in range(0,10000,int(step/2)):
    #print(i)
    run_acc_extended=run_acc_extended.append(run_acc.iloc[i:i+step])
    run_gyro_extended=run_gyro_extended.append(run_gyro.iloc[i:i+step])
    sit_acc_extended=sit_acc_extended.append(sit_acc.iloc[i:i+step])
    sit_gyro_extended=sit_gyro_extended.append(sit_gyro.iloc[i:i+step])
    walk_acc_extended=walk_acc_extended.append(walk_acc.iloc[i:i+step])
    walk_gyro_extended=walk_gyro_extended.append(walk_gyro.iloc[i:i+step])
    lay_acc_extended=lay_acc_extended.append(lay_acc.iloc[i:i+step])
    lay_gyro_extended=lay_gyro_extended.append(lay_gyro.iloc[i:i+step])



# run_acc_extended.columns=['x','y','z']
# run_gyro_extended.columns=['x','y','z']
# sit_acc_extended.columns=['x','y','z']
# sit_gyro_extended.columns=['x','y','z']
# walk_acc_extended.columns=['x','y','z']
# walk_gyro_extended.columns=['x','y','z']
# lay_acc_extended.columns=['x','y','z']
# lay_gyro_extended.columns=['x','y','z']

In [242]:
run_acc_extended.shape

(20000, 3)

In [243]:
sit_acc_extended.shape

(20000, 3)

In [244]:
walk_acc_extended.shape

(20000, 3)

In [245]:
walk_gyro_extended.shape

(19999, 3)

In [246]:
lay_acc_extended.shape

(20000, 3)

In [247]:
test=run_acc_extended.iloc[0:0+step,0].to_frame().T

In [248]:
test

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
0,-0.010774,0.715268,0.877475,0.705691,-0.076016,-1.429937,-1.756147,1.355118,-2.525284,-4.44304,...,0.0826,-1.707664,-3.358466,-1.350928,1.032499,-3.894169,-1.723227,5.094263,3.6338,6.215348

In [249]:
test.append(run_acc_extended.iloc[50:50+step,0].to_frame().T)

,0,1,2,3,4,5,6,7,8,9,...,65,66,67,68,69,70,71,72,73,74
0,-0.010774,0.715268,0.877475,0.705691,-0.076016,-1.429937,-1.756147,1.355118,-2.525284,-4.44304,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-8.703522,-0.949301,1.95726,1.529895,2.334945,0.811036,0.794276,-0.580594,-1.127669,-1.735796

In [250]:
run_acc_extended_x=pd.DataFrame()
run_gyro_extended_x=pd.DataFrame()
sit_acc_extended_x=pd.DataFrame()
sit_gyro_extended_x=pd.DataFrame()
walk_acc_extended_x=pd.DataFrame()
walk_gyro_extended_x=pd.DataFrame()
lay_acc_extended_x=pd.DataFrame()
lay_gyro_extended_x=pd.DataFrame()


run_acc_extended_y=pd.DataFrame()
run_gyro_extended_y=pd.DataFrame()
sit_acc_extended_y=pd.DataFrame()
sit_gyro_extended_y=pd.DataFrame()
walk_acc_extended_y=pd.DataFrame()
walk_gyro_extended_y=pd.DataFrame()
lay_acc_extended_y=pd.DataFrame()
lay_gyro_extended_y=pd.DataFrame()


run_acc_extended_z=pd.DataFrame()
run_gyro_extended_z=pd.DataFrame()
sit_acc_extended_z=pd.DataFrame()
sit_gyro_extended_z=pd.DataFrame()
walk_acc_extended_z=pd.DataFrame()
walk_gyro_extended_z=pd.DataFrame()
lay_acc_extended_z=pd.DataFrame()
lay_gyro_extended_z=pd.DataFrame()




for i in range(0,19950,step):
    
    print(i)
    temp1=run_acc_extended.iloc[i:i+step,0].to_frame().T
    temp1.columns=[n for n in range(0,50)]
    run_acc_extended_x=run_acc_extended_x.append(temp1)
    temp2=run_gyro_extended.iloc[i:i+step,0].to_frame().T
    temp2.columns=[n for n in range(0,50)]
    run_gyro_extended_x=run_gyro_extended_x.append(temp2)
    temp3=sit_acc_extended.iloc[i:i+step,0].to_frame().T
    temp3.columns=[n for n in range(0,50)]
    sit_acc_extended_x=sit_acc_extended_x.append(temp3)
    temp4=sit_gyro_extended.iloc[i:i+step,0].to_frame().T
    temp4.columns=[n for n in range(0,50)]
    sit_gyro_extended_x=sit_gyro_extended_x.append(temp4)
    temp5=walk_acc_extended.iloc[i:i+step,0].to_frame().T
    temp5.columns=[n for n in range(0,50)]
    walk_acc_extended_x=walk_acc_extended_x.append(temp5)
    temp6=walk_gyro_extended.iloc[i:i+step,0].to_frame().T
    temp6.columns=[n for n in range(0,50)]
    walk_gyro_extended_x=walk_gyro_extended_x.append(temp6)
    temp7=lay_acc_extended.iloc[i:i+step,0].to_frame().T
    temp7.columns=[n for n in range(0,50)]
    lay_acc_extended_x=lay_acc_extended_x.append(temp7)
    temp8=lay_gyro_extended.iloc[i:i+step,0].to_frame().T
    temp8.columns=[n for n in range(0,50)]
    lay_gyro_extended_x=lay_gyro_extended_x.append(temp8)


    temp9=run_acc_extended.iloc[i:i+step,1].to_frame().T
    temp9.columns=[n for n in range(0,50)]
    run_acc_extended_y=run_acc_extended_y.append(temp9)
    temp10=run_gyro_extended.iloc[i:i+step,1].to_frame().T
    temp10.columns=[n for n in range(0,50)]
    run_gyro_extended_y=run_gyro_extended_y.append(temp10)
    temp11=sit_acc_extended.iloc[i:i+step,1].to_frame().T
    temp11.columns=[n for n in range(0,50)]
    sit_acc_extended_y=sit_acc_extended_y.append(temp11)
    temp12=sit_gyro_extended.iloc[i:i+step,1].to_frame().T
    temp12.columns=[n for n in range(0,50)]
    sit_gyro_extended_y=sit_gyro_extended_y.append(temp12)
    temp13=walk_acc_extended.iloc[i:i+step,1].to_frame().T
    temp13.columns=[n for n in range(0,50)]
    walk_acc_extended_y=walk_acc_extended_y.append(temp13)
    temp14=walk_gyro_extended.iloc[i:i+step,1].to_frame().T
    temp14.columns=[n for n in range(0,50)]
    walk_gyro_extended_y=walk_gyro_extended_y.append(temp14)
    temp15=lay_acc_extended.iloc[i:i+step,1].to_frame().T
    temp15.columns=[n for n in range(0,50)]
    lay_acc_extended_y=lay_acc_extended_y.append(temp15)
    temp16=lay_gyro_extended.iloc[i:i+step,1].to_frame().T
    temp16.columns=[n for n in range(0,50)]
    lay_gyro_extended_y=lay_gyro_extended_y.append(temp16)


    temp17=run_acc_extended.iloc[i:i+step,2].to_frame().T
    temp17.columns=[n for n in range(0,50)]
    run_acc_extended_z=run_acc_extended_z.append(temp17)
    temp18=run_gyro_extended.iloc[i:i+step,2].to_frame().T
    temp18.columns=[n for n in range(0,50)]
    run_gyro_extended_z=run_gyro_extended_z.append(temp18)
    temp19=sit_acc_extended.iloc[i:i+step,2].to_frame().T
    temp19.columns=[n for n in range(0,50)]
    sit_acc_extended_z=sit_acc_extended_z.append(temp19)
    temp20=sit_gyro_extended.iloc[i:i+step,2].to_frame().T
    temp20.columns=[n for n in range(0,50)]
    sit_gyro_extended_z=sit_gyro_extended_z.append(temp20)
    temp21=walk_acc_extended.iloc[i:i+step,2].to_frame().T
    temp21.columns=[n for n in range(0,50)]
    walk_acc_extended_z=walk_acc_extended_z.append(temp21)
    temp22=walk_gyro_extended.iloc[i:i+step,2].to_frame().T
    temp22.columns=[n for n in range(0,50)]
    walk_gyro_extended_z=walk_gyro_extended_z.append(temp22)
    temp23=lay_acc_extended.iloc[i:i+step,2].to_frame().T
    temp23.columns=[n for n in range(0,50)]
    lay_acc_extended_z=lay_acc_extended_z.append(temp23)
    temp24=lay_gyro_extended.iloc[i:i+step,2].to_frame().T
    temp24.columns=[n for n in range(0,50)]
    lay_gyro_extended_z=lay_gyro_extended_z.append(temp24)

    
    
#     run_acc_extended_x=run_acc_extended_x.append(pd.DataFrame(run_acc_extended.iloc[i:i+step,0]).T)
#     run_gyro_extended_x=run_gyro_extended_x.append(pd.DataFrame(run_gyro_extended.iloc[i:i+step,0]).T)
#     sit_acc_extended_x=sit_acc_extended_x.append(pd.DataFrame(sit_acc_extended.iloc[i:i+step,0]).T)
#     sit_gyro_extended_x=sit_gyro_extended_x.append(pd.DataFrame(sit_gyro_extended.iloc[i:i+step,0]).T)
#     walk_acc_extended_x=walk_acc_extended_x.append(pd.DataFrame(walk_acc_extended.iloc[i:i+step,0]).T)
#     walk_gyro_extended_x=walk_gyro_extended_x.append(pd.DataFrame(walk_gyro_extended.iloc[i:i+step,0]).T)
#     lay_acc_extended_x=lay_acc_extended_x.append(pd.DataFrame(lay_acc_extended.iloc[i:i+step,0]).T)
#     lay_gyro_extended_x=lay_gyro_extended_x.append(pd.DataFrame(lay_gyro_extended.iloc[i:i+step,0]).T)

#     run_acc_extended_y=run_acc_extended_y.append(pd.DataFrame(run_acc_extended.iloc[i:i+step,1]).T)
#     run_gyro_extended_y=run_gyro_extended_y.append(pd.DataFrame(run_gyro_extended.iloc[i:i+step,1]).T)
#     sit_acc_extended_y=sit_acc_extended_y.append(pd.DataFrame(sit_acc_extended.iloc[i:i+step,1]).T)
#     sit_gyro_extended_y=sit_gyro_extended_y.append(pd.DataFrame(sit_gyro_extended.iloc[i:i+step,1]).T)
#     walk_acc_extended_y=walk_acc_extended_y.append(pd.DataFrame(walk_acc_extended.iloc[i:i+step,1]).T)
#     walk_gyro_extended_y=walk_gyro_extended_y.append(pd.DataFrame(walk_gyro_extended.iloc[i:i+step,1]).T)
#     lay_acc_extended_y=lay_acc_extended_y.append(pd.DataFrame(lay_acc_extended.iloc[i:i+step,1]).T)
#     lay_gyro_extended_y=lay_gyro_extended_y.append(pd.DataFrame(lay_gyro_extended.iloc[i:i+step,1]).T)

#     run_acc_extended_z=run_acc_extended_z.append(pd.DataFrame(run_acc_extended.iloc[i:i+step,2]).T)
#     run_gyro_extended_z=run_gyro_extended_z.append(pd.DataFrame(run_gyro_extended.iloc[i:i+step,2]).T)
#     sit_acc_extended_z=sit_acc_extended_z.append(pd.DataFrame(sit_acc_extended.iloc[i:i+step,2]).T)
#     sit_gyro_extended_z=sit_gyro_extended_z.append(pd.DataFrame(sit_gyro_extended.iloc[i:i+step,2]).T)
#     walk_acc_extended_z=walk_acc_extended_z.append(pd.DataFrame(walk_acc_extended.iloc[i:i+step,2]).T)
#     walk_gyro_extended_z=walk_gyro_extended_z.append(pd.DataFrame(walk_gyro_extended.iloc[i:i+step,2]).T)
#     lay_acc_extended_z=lay_acc_extended_z.append(pd.DataFrame(lay_acc_extended.iloc[i:i+step,2]).T)
#     lay_gyro_extended_z=lay_gyro_extended_z.append(pd.DataFrame(lay_gyro_extended.iloc[i:i+step,2]).T)

0
50
100
150
200
250
300
350
400
450
500
550
600
650
700
750
800
850
900
950
1000
1050
1100
1150
1200
1250
1300
1350
1400
1450
1500
1550
1600
1650
1700
1750
1800
1850
1900
1950
2000
2050
2100
2150
2200
2250
2300
2350
2400
2450
2500
2550
2600
2650
2700
2750
2800
2850
2900
2950
3000
3050
3100
3150
3200
3250
3300
3350
3400
3450
3500
3550
3600
3650
3700
3750
3800
3850
3900
3950
4000
4050
4100
4150
4200
4250
4300
4350
4400
4450
4500
4550
4600
4650
4700
4750
4800
4850
4900
4950
5000
5050
5100
5150
5200
5250
5300
5350
5400
5450
5500
5550
5600
5650
5700
5750
5800
5850
5900
5950
6000
6050
6100
6150
6200
6250
6300
6350
6400
6450
6500
6550
6600
6650
6700
6750
6800
6850
6900
6950
7000
7050
7100
7150
7200
7250
7300
7350
7400
7450
7500
7550
7600
7650
7700
7750
7800
7850
7900
7950
8000
8050
8100
8150
8200
8250
8300
8350
8400
8450
8500
8550
8600
8650
8700
8750
8800
8850
8900
8950
9000
9050
9100
9150
9200
9250
9300
9350
9400
9450
9500
9550
9600
9650
9700
9750
9800
9850
9900
9950
10000
10050
10100
10150
10200
10250
10300
10350
10400
10450
10500
10550
10600
10650
10700
10750
10800
10850
10900
10950
11000
11050
11100
11150
11200
11250
11300
11350
11400
11450
11500
11550
11600
11650
11700
11750
11800
11850
11900
11950
12000
12050
12100
12150
12200
12250
12300
12350
12400
12450
12500
12550
12600
12650
12700
12750
12800
12850
12900
12950
13000
13050
13100
13150
13200
13250
13300
13350
13400
13450
13500
13550
13600
13650
13700
13750
13800
13850
13900
13950
14000
14050
14100
14150
14200
14250
14300
14350
14400
14450
14500
14550
14600
14650
14700
14750
14800
14850
14900
14950
15000
15050
15100
15150
15200
15250
15300
15350
15400
15450
15500
15550
15600
15650
15700
15750
15800
15850
15900
15950
16000
16050
16100
16150
16200
16250
16300
16350
16400
16450
16500
16550
16600
16650
16700
16750
16800
16850
16900
16950
17000
17050
17100
17150
17200
17250
17300
17350
17400
17450
17500
17550
17600
17650
17700
17750
17800
17850
17900
17950
18000
18050
18100
18150
18200
18250
18300
18350
18400
18450
18500
18550
18600
18650
18700
18750
18800
18850
18900
18950
19000
19050
19100
19150
19200
19250
19300
19350
19400
19450
19500
19550
19600
19650
19700
19750
19800
19850
19900

In [251]:
run_acc_extended_x.shape

(399, 50)

In [256]:
#run_acc_extended_x['y']=1

run_acc_extended_x['y']=1
run_gyro_extended_x['y']=1
run_acc_extended_y['y']=1
run_gyro_extended_y['y']=1
run_acc_extended_z['y']=1
run_gyro_extended_z['y']=1

sit_acc_extended_x['y']=2
sit_gyro_extended_x['y']=2
sit_acc_extended_y['y']=2
sit_gyro_extended_y['y']=2
sit_acc_extended_z['y']=2
sit_gyro_extended_z['y']=2

walk_acc_extended_x['y']=3
walk_gyro_extended_x['y']=3
walk_acc_extended_y['y']=3
walk_gyro_extended_y['y']=3
walk_acc_extended_z['y']=3
walk_gyro_extended_z['y']=3

lay_acc_extended_x['y']=4
lay_gyro_extended_x['y']=4
lay_acc_extended_y['y']=4
lay_gyro_extended_y['y']=4
lay_acc_extended_z['y']=4
lay_gyro_extended_z['y']=4

In [258]:

sit_acc_extended_x.head()

,0,1,2,3,4,5,6,7,8,9,...,41,42,43,44,45,46,47,48,49,y
0,-0.246004,-0.295085,-0.304662,-0.299275,-0.313042,-0.290895,-0.305261,-0.332794,-0.344166,-0.286706,...,-0.349553,-0.366911,-0.377685,-0.410606,-0.374094,-0.308253,-0.307056,-0.309451,-0.300472,2
0,-0.301669,-0.299874,-0.281319,-0.285509,-0.277129,-0.275932,-0.269348,-0.297480,-0.263362,-0.288501,...,-0.321422,-0.314838,-0.286706,-0.271143,-0.265158,-0.317232,-0.319027,-0.336385,-0.322619,2
0,-0.325013,-0.364517,-0.354342,-0.340575,-0.323816,-0.310049,-0.298677,-0.283114,-0.320823,-0.354940,...,-0.311845,-0.291494,-0.282516,-0.317830,-0.325013,-0.319626,-0.325013,-0.278326,-0.320224,2
0,-0.331597,-0.303465,-0.307056,-0.323816,-0.302867,-0.297480,-0.297480,-0.292691,-0.283114,-0.287903,...,-0.306458,-0.294487,-0.308852,-0.283713,-0.292093,-0.269348,-0.275333,-0.282516,-0.307056,2
0,-0.334590,-0.330998,-0.275333,-0.256778,-0.272340,-0.293290,-0.271143,-0.296881,-0.301071,-0.264559,...,-0.291494,-0.296881,-0.293888,-0.257975,-0.262165,-0.283114,-0.308253,-0.293290,-0.283114,2

In [274]:
acc_x=pd.concat([run_acc_extended_x,sit_acc_extended_x,walk_acc_extended_x,lay_acc_extended_x])
#acc_x=acc_x.sample(frac=1).reset_index(drop=True)
acc_y=pd.concat([run_acc_extended_y,sit_acc_extended_y,walk_acc_extended_y,lay_acc_extended_y])
#acc_y=acc_y.sample(frac=1).reset_index(drop=True)
acc_z=pd.concat([run_acc_extended_z,sit_acc_extended_z,walk_acc_extended_z,lay_acc_extended_z])
#acc_z=acc_z.sample(frac=1).reset_index(drop=True)

gyro_x=pd.concat([run_gyro_extended_x,sit_gyro_extended_x,walk_gyro_extended_x,lay_gyro_extended_x])
#gyro_x=gyro_x.sample(frac=1).reset_index(drop=True)
gyro_y=pd.concat([run_gyro_extended_y,sit_gyro_extended_y,walk_gyro_extended_y,lay_gyro_extended_y])
#gyro_y=gyro_y.sample(frac=1).reset_index(drop=True)
gyro_z=pd.concat([run_gyro_extended_z,sit_gyro_extended_z,walk_gyro_extended_z,lay_gyro_extended_z])
#gyro_z=gyro_z.sample(frac=1).reset_index(drop=True)

In [275]:
acc_x.to_csv("My_CSV_Data/acc_x.csv",index=False)
acc_y.to_csv("My_CSV_Data/acc_y.csv",index=False)
acc_z.to_csv("My_CSV_Data/acc_z.csv",index=False)

gyro_x.to_csv("My_CSV_Data/gyro_x.csv",index=False)
gyro_y.to_csv("My_CSV_Data/gyro_y.csv",index=False)
gyro_z.to_csv("My_CSV_Data/gyro_z.csv",index=False)

In [276]:
gyro_z.head()

,0,1,2,3,4,5,6,7,8,9,...,41,42,43,44,45,46,47,48,49,y
2,-0.072438,-0.072438,-0.414388,-0.653007,-0.741424,-0.725445,-0.181095,0.738228,1.250620,0.680704,...,-0.581634,-0.247141,0.337689,1.208010,1.264469,1.209075,1.001349,-0.041545,-1.512675,1
2,-0.689226,-0.917193,-0.420779,-0.450607,0.491087,0.847950,0.276969,0.173638,0.465521,0.552872,...,1.245294,0.728641,0.374973,0.318514,0.422910,0.201335,-0.019175,-0.132093,-0.289752,1
2,-1.825863,-1.643703,-1.290035,-0.694552,-0.042611,0.335558,0.428236,0.338754,-0.041545,-0.491087,...,0.385626,0.185356,0.054328,-0.272708,-0.644485,-0.895887,-1.192031,-1.201618,0.504935,1
2,-0.447411,-0.355798,0.018109,0.463390,1.618137,2.343582,1.497762,0.527306,-1.136637,-2.161421,...,2.733469,0.341950,-1.766208,-2.083657,-1.870604,-1.476457,-1.392301,-0.997088,-0.255663,1
2,1.393366,1.262338,0.828776,0.484695,0.389887,0.461260,0.249272,-0.078830,-0.160855,-0.219444,...,0.458064,0.112918,-0.155529,-0.091613,-0.180030,-0.515588,-0.288687,0.175769,0.785100,1